{% set version = "0.2.2" %}

package:
  name: strbioinfo
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/77/26/a44051e52123d5a32c77c7600bc13dc6c275782d578258693e54d831f9fc/StrBioInfo-{{ version }}.tar.gz
  sha256: dc966381c8b7a2559dd18e59fd8b47974e902f671ea442c62a92eecb803c0ccc

requirements:
  host:
    - python >=2.7,<3.0.0a0
    - numpy >=1.8.1,<2.0.0
    - scipy >=1.0.0,<1.5.0
    - beautifulsoup4 >=4.3.2,<5.0.0
    - pynion >=0.0.4
    - lxml
  run:
    - python >=2.7,<3.0.0a0
    - numpy >=1.8.1,<2.0.0
    - scipy >=1.0.0,<1.5.0
    - beautifulsoup4 >=4.3.2,<5.0.0
    - pynion >=0.0.4
    - lxml

build:
  number: 0

about:
  home: https://pypi.org/project/StrBioInfo/
  license: MIT
  license_family: MIT
  license_file: PKG-INFO
  summary: The StructuralBioInformatics Library
